# Generated by Django 6.0.3 on 2026-03-30 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('simbolo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_transaccion', models.CharField(choices=[('deposito', 'Depósito'), ('retiro', 'Retiro'), ('transferencia', 'Transferencia')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='wallet.moneda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='wallet.usuario')),
            ],
        ),
    ]
